# Cloudflare Worker configuration for voicemode.sh
name = "voicemode-installer"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Your Cloudflare account ID (get from dashboard)
# account_id = "your-account-id"

# Custom domain (temporarily commented to deploy - DNS records need to be managed separately)
# routes = [
#   { pattern = "voicemode.sh", custom_domain = true },
#   { pattern = "www.voicemode.sh", custom_domain = true }
# ]

# Environment variables (optional)
[vars]
GITHUB_REPO = "mbailey/voicemode"
INSTALL_SCRIPT_PATH = "docs/web/install.sh"

# Cache configuration (uncomment and configure when needed)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Analytics (optional - uncomment when Analytics Engine is enabled)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"